# Generated by Django 5.1.1 on 2024-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
