# Generated by Django 5.1.1 on 2024-10-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='place',
            field=models.TextField(),
        ),
    ]
