# Generated by Django 5.1.1 on 2024-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_alert_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='alert_vidoes'),
        ),
    ]
